parameters:
    softunibundle.entity.post: 'SoftuniBlogBundle\Entity\Post'
    softunibundle.service.post_manager: 'SoftuniBlogBindle\Services\PostManager'
services:
    softuni.blog.post_manager:
        class: '%softunibundle.service.post_manager%'
        arguments:
            entityManager: '@doctrine.orm.entity_manager'
            class: '%softunibundle.entity.post%'
            container: '@service_container'
