user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

softuni_blog:
    resource: "@SoftuniBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
