# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.product_pic_uploader:
        class: SoftUniBundle\Services\FileUploader
        arguments: ['%product_pic_dir%', "@doctrine.orm.entity_manager"]

    app.product-category_pic_uploader:
        class: SoftUniBundle\Services\FileUploader
        arguments: ['%category_pic_dir%', "@doctrine.orm.entity_manager"]

    app.email_sender:
        class: SoftUniBundle\Services\EmailSender
        arguments: ["@mailer", "@doctrine.orm.entity_manager"]

    app.product_manager:
        class: SoftUniBundle\Services\ProductManager
        arguments: ["@doctrine.orm.entity_manager","@app.product_pic_uploader"]

    app.product_category_manager:
        class: SoftUniBundle\Services\ProductCategoryManager
        arguments: ["@doctrine.orm.entity_manager", "@app.product_pic_uploader"]


    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
