<?php

namespace SoftUniBundle\Repository;

/**
 * SpamListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpamListRepository extends \Doctrine\ORM\EntityRepository
{
}
